# Generated by Django 5.2.17 on 2026-08-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('stores', '0003_agrovetstore_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'started'), ('arrived', 'arrived')], default='started', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to='customers.customeraccount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_visits', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='stores.agrovetstore')),
            ],
            options={
                'verbose_name': 'store visit',
                'verbose_name_plural': 'store visits',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('account', 'store'), name='visits_one_open_started_per_account_store')],
            },
        ),
    ]
