# Generated by Django 5.2.17 on 2026-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('farm_name', models.CharField(blank=True, max_length=120)),
                ('farm_type', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customer account',
                'verbose_name_plural': 'customer accounts',
                'ordering': ['full_name', 'phone'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP verification',
                'verbose_name_plural': 'OTP verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_used', '-created_at'], name='customers_o_phone_n_e38dea_idx')],
            },
        ),
    ]
