# Generated by Django 5.2.16 on 2026-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'payment transaction', 'verbose_name_plural': 'payment transactions'},
        ),
        migrations.RenameField(
            model_name='mpesatransaction',
            old_name='raw_callback',
            new_name='raw_webhook',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='merchant_request_id',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack subaccount code snapshotted at charge time', max_length=64),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='kind',
            field=models.CharField(choices=[('charge', 'Charge'), ('transfer', 'Transfer')], max_length=16),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=16),
        ),
    ]
