# Generated by Django 5.2.16 on 2026-08-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrovetStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('town', models.CharField(max_length=80)),
                ('county', models.CharField(max_length=80)),
                ('till', models.CharField(max_length=20)),
                ('attendant_phone', models.CharField(max_length=20)),
                ('open', models.BooleanField(default=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agrovet store',
                'verbose_name_plural': 'agrovet stores',
            },
        ),
    ]
