# Generated by Django 5.2.16 on 2026-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrovetstore',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack subaccount code for split settlements to this agrovet', max_length=64),
        ),
    ]
