# Generated by Django 5.2.17 on 2026-08-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_agrovetstore_paystack_subaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrovetstore',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Store map pin — used for customer Get Directions / arrival.', null=True),
        ),
        migrations.AddField(
            model_name='agrovetstore',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Store map pin — used for customer Get Directions / arrival.', null=True),
        ),
    ]
